#
# ~/.bash_aliases
#

shopt -s expand_aliases # get aliases working in vim
alias ls='ls --color=auto'
alias vi='vim'
alias sour='source $HOME/.bashrc'
# monitor configuration
alias hdmi='xrandr --output eDP1 --off --output HDMI1 --auto'
alias edp1='xrandr --output HDMI1 --off --output eDP1 --auto'
# save and jump to directory and file locations
alias sv='pwd > ~/.svdir && [ -f ~/.svfile ] && rm ~/.svfile'
alias jp='[ -f ~/.svdir ] && cd $(cat ~/.svdir)'
alias jpf='[ -f ~/.svdir ] && [ -f ~/.svfile ] && cd $(cat ~/.svdir) && vim $(cat ~/.svfile)'
# jump to saved documentation
alias archwiki='cd /usr/share/doc/arch-wiki/html/en'
alias pyref='firefox /usr/local/share/doc/python-3.4.1-docs-html/index.html'
alias noderef='firefox /usr/local/share/doc/nodejs-docs/nodejs-docs.html'
alias jqref='firefox /usr/local/share/doc/jqapi/index.html'
alias expressref='firefox /usr/local/share/doc/expressjs-docs/expressjs-docs.html'
# wifi
alias wf='sudo wifi-find'
alias wfr='sudo systemctl restart netctl-auto@wlp1s0'
# pacman
alias pacsave='pacman -Qetnq > $HOME/.arch_config/paclist.txt'
function pac {
  sudo pacman -S $@
  pacsave
}
# switch ssh_keys
alias mfkeys='cp ~/.ssh/backup_keys/id_rsa_benforged ~/.ssh/id_rsa && cp ~/.ssh/backup_keys/id_rsa_benforged.pub ~/.ssh/id_rsa.pub'
alias defkeys='cp ~/.ssh/backup_keys/* ~/.ssh/'
# markforged specific
alias cs='cd ~/programs/markforged/CarbonSlicer'
alias cr='coffee targets/development/carbonslicer.coffee'
alias ei='cd ~/programs/markforged/Eiger'
alias ma='cd ~/programs/markforged/Matterhorn'
alias gc='grunt compile'
