#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

source $HOME/.bash_aliases
source $HOME/programs/markforged/creds

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
