#
# ~/.bash_aliases
#

shopt -s expand_aliases # get aliases working in vim
alias ls='ls --color=auto'
alias vi='vim'
alias sv='pwd > ~/.svdir && rm ~/.svfile'
alias jp='[ -f ~/.svdir ] && cd $(cat ~/.svdir)'
alias jpf='[ -f ~/.svdir ] && cd $(cat ~/.svdir)'
alias jpf='[ -f ~/.svdir ] && [ -f ~/.svfile ] && cd $(cat ~/.svdir) && vim $(cat ~/.svfile)'
alias sour='source $HOME/.bashrc'
alias coffee='./node_modules/coffee-script/bin/coffee'
alias archwiki='cd /usr/share/doc/arch-wiki/html/en'
alias pyref='firefox /usr/local/share/doc/python-3.4.1-docs-html/index.html'
alias noderef='firefox /usr/local/share/doc/nodejs-docs/nodejs-docs.html'
alias jqref='firefox /usr/local/share/doc/jqapi/index.html'
alias expressref='firefox /usr/local/share/doc/expressjs-docs/expressjs-docs.html'
alias wf='sudo wifi-find'
alias wfr='sudo systemctl restart netctl-auto@wlp1s0'
alias pacsave='pacman -Qetnq > $HOME/.arch_config/paclist.txt'
function pac {
  sudo pacman -S $@
  pacsave
}
