#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# Aliases
alias ls='ls --color=auto'
alias vi='vim'
alias sour="source $HOME/.bashrc"
alias archwiki="cd /usr/share/doc/arch-wiki/html"
alias pyref="firefox /usr/local/share/doc/python-3.4.1-docs-html/index.html"
alias noderef="firefox /usr/local/share/doc/nodejs-docs/nodejs-docs.html"
alias jqref="firefox /usr/local/share/doc/jqapi/index.html"
alias expressref="firefox /usr/local/share/doc/expressjs-docs/expressjs-docs.html"
alias wf="sudo wifi-find"
alias wfr="sudo systemctl restart netctl-auto@wlp1s0"
alias pacsave="pacman -Qetn | cut -d' ' -f1 > $HOME/.arch_config/paclist.txt"
function pac {
  sudo pacman -S $@
  pacsave
}

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
