# Set cursor to arrow instead of cross
xsetroot -cursor_name left_ptr
# Fix top row keys
xbindkeys
# Change terminal colors
xrdb ~/.Xresources
# Map search key to escape
xmodmap ~/.Xmodmap
# Disable touchpad taps while typing
syndaemon -t -k -i 1 &
# Start xmonad
exec xmonad
