# Set cursor to arrow instead of cross
xsetroot -cursor_name left_ptr
# Start pulseaudio
/usr/bin/start-pulseaudio-x11
# Fix top row keys
xbindkeys
# Change terminal colors
xrdb ~/.Xresources
# Map search key to escape
xmodmap ~/.Xmodmap
# Disable touchpad taps while typing
syndaemon -t -k -i 2 &
# Start xmonad
exec xmonad
