set nocompatible
set history=1000
" Let vim use bash aliases
let $BASH_ENV="~/.bash_aliases"

" Load plugins with Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'digitaltoad/vim-jade'
Plugin 'digitaltoad/vim-pug'
Plugin 'groenewege/vim-less'
Plugin 'posva/vim-vue'

call vundle#end()

filetype plugin indent on

" Set tabs to two spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set shiftround
" Set python tabs specifically
autocmd FileType python set tabstop=2|set shiftwidth=2|set softtabstop=2

" Enable syntax highlighting
syntax on

" Change colorscheme
set background=dark
colorscheme solarized

" Show line numbers
set nu

" Show filename at bottom of window
set ls=2

" Make tab-completion better
set wildmode=longest,list,full
set wildmenu

" Autoupdate files from the outside
set autoread

" pwd should be this file, not some other madness
set autochdir

" Disable backup
set nobackup
set nowb
set noswapfile

" Delete trailing whitespace on save
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
au BufWrite * :call DeleteTrailingWS()

" Treat csjx files as coffeescript
au BufNewFile,BufRead *.cjsx set filetype=coffee

" Set leader and localleader
:let mapleader = ","
:let maplocalleader = "\\"

" Useful mappings
" Edit my vimrc
:nnoremap <leader>ev :vsp $MYVIMRC<cr>
:nnoremap <leader>sv :source $MYVIMRC<cr>
" Toggle NERDTree
:nnoremap <leader>nt :NERDTreeToggle<cr>
" Copy-paste with clipboard
:vnoremap <leader>cc :w !xsel -ib<cr>
:nnoremap <leader>vv :r !xsel -b<cr>
" Save current directory and file so I can jump to them
:noremap <C-k> :redi! > $HOME/.svdir<cr>:echon expand('%:p:h')<cr>:redi END<cr>:redi! > $HOME/.svfile<cr>:echon expand('%:t')<cr>:redi END<cr>:!sed -i -e "1d" $HOME/.svdir $HOME/.svfile<cr>
" Tab shortcuts
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <silent> <A-Left> :execute 'silent! tabmove ' . (tabpagenr()-2)<CR>
nnoremap <silent> <A-Right> :execute 'silent! tabmove ' . tabpagenr()<CR>

" Highlight current line and column as well as the 80th column
set cursorline
set colorcolumn=80,120
highlight ColorColumn ctermbg=0

" CtrlP ignored files
let g:ctrlp_custom_ignore = '\v[\/](node_modules)$'
