set nocompatible
set history=1000
" Let vim use bash aliases
let $BASH_ENV="~/.bash_aliases"

" Load plugins with Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
Bundle 'kchmck/vim-coffee-script'
Bundle 'digitaltoad/vim-jade'
Bundle 'groenewege/vim-less'

call vundle#end()

filetype plugin indent on

" Set tabs to two spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set shiftround
" Set python tabs specifically
autocmd FileType python set tabstop=2|set shiftwidth=2|set softtabstop=2

" Enable syntax highlighting
syntax on

" Change colorscheme
set background=dark
colorscheme solarized

" Show line numbers
set nu

" Show filename at bottom of window
set ls=2

" Make tab-completion better
set wildmode=longest,list,full
set wildmenu

" Autoupdate files from the outside
set autoread

" pwd should be this file, not some other madness
set autochdir

" Disable backup
set nobackup
set nowb
set noswapfile

" Delete trailing whitespace on save
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
au BufWrite * :call DeleteTrailingWS()

" Set leader and localleader
:let mapleader = ","
:let maplocalleader = "\\"

" Useful mappings
" Edit my vimrc
:nnoremap <leader>ev :vsp $MYVIMRC<cr>
:nnoremap <leader>sv :source $MYVIMRC<cr>
" Toggle NERDTree
:nnoremap <leader>nt :NERDTreeToggle<cr>
" Copy-paste with clipboard
:vnoremap <leader>cc :w !xsel -ib<cr>
:nnoremap <leader>vv :r !xsel -b<cr>
" Save current directory and file so I can jump to them
:noremap <C-k> :redi! > $HOME/.svdir<cr>:echon expand('%:p:h')<cr>:redi END<cr>:redi! > $HOME/.svfile<cr>:echon expand('%:t')<cr>:redi END<cr>:!sed -i -e "1d" $HOME/.svdir $HOME/.svfile<cr>

" Highlight current line and column as well as the 80th column
set cursorline
set colorcolumn=80
highlight ColorColumn ctermbg=0
