#!/bin/bash

function bat {
  state=$(acpi -b)
  percent=$(echo $state | sed 's/^.* \([0-9]\+%\).*$/\1/')
  if [[ $percent == '100%' ]]
  then
    printf "AC 100%% full"
  else
    timestr=$(echo $state | sed 's/^.* 0*\([0-9]\+\):\([0-9]\+\).*$/\1h\2m/')
    timestr=$(echo $timestr | sed 's/^0h//')
    charging="Bat"
    timemod="remaining"
    if [[ $(echo $state | grep Discharging) == '' ]]
    then
      charging="AC"
      timemod="until full"
    fi
    printf "%s %s, %s %s" "$charging" "$percent" "$timestr" "$timemod"
  fi
}

while true ; do
    dt=`date +"%a %b %d %l:%M %p "`
    printf "%s | %s\n" "$dt" "$(bat)"
    sleep 2
done | dzen2 -e ''
